# Generated by Django 5.0.6 on 2025-07-27 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city'],
                'unique_together': {('city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', max_length=1)),
                ('show_humidity', models.BooleanField(default=True)),
                ('show_wind', models.BooleanField(default=True)),
                ('show_pressure', models.BooleanField(default=False)),
                ('refresh_interval', models.PositiveIntegerField(default=30, help_text='Auto-refresh interval in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wheatherapp.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(help_text='Feels like temperature in Celsius')),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('pressure', models.IntegerField(help_text='Atmospheric pressure in hPa')),
                ('wind_speed', models.FloatField(help_text='Wind speed in meter/sec')),
                ('wind_degree', models.IntegerField(help_text='Wind direction in degrees')),
                ('weather_condition', models.CharField(max_length=100)),
                ('weather_description', models.TextField()),
                ('visibility', models.IntegerField(help_text='Visibility in meters')),
                ('cloudiness', models.IntegerField(help_text='Cloudiness percentage')),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('timezone_offset', models.IntegerField(help_text='Shift in seconds from UTC')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='wheatherapp.location')),
            ],
            options={
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
