# Generated by Django 5.0.6 on 2025-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(blank=True, default=None, help_text='Feels like temperature in Celsius', null=True),
        ),
    ]
