# Generated by Django 5.0.6 on 2025-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheatherapp', '0002_alter_weatherdata_feels_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='cloudiness',
            field=models.IntegerField(blank=True, help_text='Cloudiness percentage', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.IntegerField(blank=True, help_text='Humidity percentage', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='pressure',
            field=models.IntegerField(blank=True, help_text='Atmospheric pressure in hPa', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timezone_offset',
            field=models.IntegerField(blank=True, help_text='Shift in seconds from UTC', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='visibility',
            field=models.IntegerField(blank=True, help_text='Visibility in meters', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weather_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_degree',
            field=models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(blank=True, help_text='Wind speed in meter/sec', null=True),
        ),
    ]
